apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: labour-hiring-system
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None  # Headless service for stable DNS

